# Generated by Django 5.0.7 on 2025-02-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
    ]
